AWSTemplateFormatVersion: "2010-09-09"

Description: An Aurora RDS Instance with AutoScaling

Parameters:
  pAdminUser:
    Description: The username for the RDS admin user
    Type: String
    Default: dbmaster

  pBacktrackWindow:
    Description: Backtrack window in seconds, only applicable for MySQL
    Type: Number

  pBackupRetention:
    Description: Backup retention period in days
    Type: Number

  pBuild:
    Description: The CodeBuild build number
    Type: Number

  pCleanBranch:
    Description: The clean branch
    Type: String

  pCreateReplica:
    Description: Create a read replica
    Type: String
    AllowedValues:
      - "true"
      - "false"

  pDatabaseInsightsMode:
    Description: enable or disable database insights
    Type: String
    AllowedValues:
      - standard
      - advanced

  pDbEngine:
    Description: The database family. aurora-mysql or aurora-postgresql
    Type: String
    AllowedValues:
      - aurora-mysql
      - aurora-postgresql

  pDbInstanceName:
    Description: The db instance name. This gets used as part of the hostname to connect to the db
    Type: String

  pDbParamGrpFamily:
    Description: The database parameter group family.
    Type: String
    AllowedValues:
      - aurora-mysql8.4
      - aurora-postgresql16
      - aurora-postgresql17
      - aurora-postgresql18

  pDbVersion:
    Description: The version of the database for the RDS instance
    Type: String

  pDeletionProtection:
    Description: Enable deletion protection
    Type: String
    AllowedValues:
      - "true"
      - "false"

  pEngineMode:
    Description: Specify the EngineMode
    Type: String
    AllowedValues:
      - provisioned
      - serverlessv2
    Default: provisioned

  pEnhancedMonitoring:
    Description: enhanced monitoring interval in seconds, 0 to disable
    Type: Number
    Default: 0

  pEnvironment:
    Description: Environment for this RDS instance
    Type: String
    AllowedValues:
      - development
      - testing
      - staging
      - production

  pExportLogs:
    Description: Enable or disable exporting logs to CloudWatch
    Type: String
    AllowedValues:
      - "true"
      - "false"

  pInstanceClass:
    Description: The RDS instance class
    Type: String

  pPerformanceInsights:
    Description: Enable performance insights
    Type: String
    AllowedValues:
      - "true"
      - "false"

  pProductName:
    Description: The product name
    Type: String

  pRdsSnapshotRestore:
    Description: The snapshot to restore from
    Type: String
    Default: "false"

  pSecretName:
    Description: The name of the secret
    Type: String

  pVpcStackName:
    Description: The name of the Bedrock VPC stack
    Type: String

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development

  IsProd: !Equals
    - !Ref pEnvironment
    - production

  RestoreFromSnapshot: !Not
    - !Equals
      - !Ref pRdsSnapshotRestore
      - "false"

  IsProvisioned: !Equals
    - !Ref pEngineMode
    - provisioned

  DatabaseInsights: !And
    - !Equals
      - !Ref pDatabaseInsightsMode
      - advanced
    - !Equals
      - !Ref pPerformanceInsights
      - "true"

  CreateReplica: !Equals
    - !Ref pCreateReplica
    - "true"

  ExportLogs: !Equals
    - !Ref pExportLogs
    - "true"

  EnhancedMonitoring: !Not
    - !Equals
      - !Ref pEnhancedMonitoring
      - 0

  HorizontalScaling: !And
    - !Equals
      - !Ref pEngineMode
      - provisioned
    - !Equals
      - !Ref pCreateReplica
      - "true"

  IsServerlessV2: !Equals
    - !Ref pEngineMode
    - serverlessv2

  IsMysql: !Equals
    - !Ref pDbEngine
    - aurora-mysql

  IsPostgres: !Equals
    - !Ref pDbEngine
    - aurora-postgresql

  PerformanceInsights: !Equals
    - !Ref pPerformanceInsights
    - "true"

Resources:
  MysqlDbInstanceParamGrp:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub ${pProductName} DB instance parameter grp
      Family: !Ref pDbParamGrpFamily
      Parameters:
        long_query_time: 2
        slow_query_log: 1
        log_queries_not_using_indexes: 0
        performance_schema: 1
    Condition: IsMysql

  PostgresDbInstanceParamGrp:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub ${pProductName} DB instance parameter grp
      Family: !Ref pDbParamGrpFamily
      Parameters:
        log_min_duration_statement: 2000
        log_statement: ddl
    Condition: IsPostgres

  MysqlClusterParamGrp:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub ${pProductName} mysql cluster param group
      Family: !Ref pDbParamGrpFamily
      Parameters:
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_database: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4
        collation_connection: utf8mb4_unicode_ci
        collation_server: utf8mb4_unicode_ci
        time_zone: Australia/Sydney
      Tags:
        - Key: Name
          Value: !Sub ${pDbParamGrpFamily}-cluster-paramgrp
    Condition: IsMysql

  PostgresClusterParamGrp:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub ${pProductName} postgres cluster param group
      Family: !Ref pDbParamGrpFamily
      Parameters:
        timezone: Australia/Sydney
      Tags:
        - Key: Name
          Value: !Sub ${pDbParamGrpFamily}-cluster-paramgrp
    Condition: IsPostgres

  DbSubnetGrp:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds: !Split
        - ','
        - !ImportValue
          Fn::Sub: ${pVpcStackName}-PriSubnets

  DbSecurityGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access from the VPC
      VpcId: !ImportValue
        Fn::Sub: ${pVpcStackName}-Vpc
      SecurityGroupIngress:
        - Description: Allow DB access from within the VPC
          IpProtocol: tcp
          FromPort: !If
            - IsMysql
            - 3306
            - 5432
          ToPort: !If
            - IsMysql
            - 3306
            - 5432
          CidrIp: !ImportValue
            Fn::Sub: ${pVpcStackName}-VpcCidr
      SecurityGroupEgress:
        - Description: Allow egress traffic to the VPC
          IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: !ImportValue
            Fn::Sub: ${pVpcStackName}-VpcCidr
      Tags:
        - Key: Name
          Value: !Sub ${pProductName} ${pEnvironment} RDS SG

  EnhancedMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      Description: !Sub Enhanced monitoring role for ${pDbInstanceName}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
    Condition: EnhancedMonitoring

  DbCluster:
    DeletionPolicy: !If
      - IsProd
      - Snapshot
      - Delete
    UpdateReplacePolicy: !If
      - IsProd
      - Snapshot
      - Delete
    Type: AWS::RDS::DBCluster
    DependsOn:
      - ErrorLogGroup
      - SlowQueryLogGroup
    Properties:
      BacktrackWindow: !If
        - IsMysql
        - !Ref pBacktrackWindow
        - !Ref AWS::NoValue
      BackupRetentionPeriod: !Ref pBackupRetention
      CopyTagsToSnapshot: true
      DatabaseInsightsMode: !Ref pDatabaseInsightsMode
      DatabaseName: !Sub ${pProductName}${pEnvironment}
      DBClusterIdentifier: !Sub ${pDbInstanceName}-cluster
      DBClusterParameterGroupName: !If
        - IsMysql
        - !Ref MysqlClusterParamGrp
        - !Ref PostgresClusterParamGrp
      DBSubnetGroupName: !Ref DbSubnetGrp
      DeletionProtection: !Ref pDeletionProtection
      EnableCloudwatchLogsExports: !If
        - ExportLogs
        - !If
          - IsMysql
          - - error
            - slowquery
          - - postgresql
        - !Ref AWS::NoValue
      Engine: !Ref pDbEngine
      EngineMode: !If
        - IsServerlessV2
        - !Ref AWS::NoValue
        - provisioned
      EngineVersion: !Ref pDbVersion
      MasterUsername: !Ref pAdminUser
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${pSecretName}:SecretString:db-password}}'
      MonitoringInterval: !Ref pEnhancedMonitoring
      MonitoringRoleArn: !If
        - EnhancedMonitoring
        - !GetAtt EnhancedMonitoringRole.Arn
        - !Ref AWS::NoValue
      PerformanceInsightsEnabled: !Ref pPerformanceInsights
      PerformanceInsightsRetentionPeriod: !If
        - PerformanceInsights
        - !If
          - DatabaseInsights
          - 465
          - 7
        - !Ref AWS::NoValue
      Port: !If
        - IsMysql
        - 3306
        - 5432
      PreferredBackupWindow: 16:00-17:00
      PreferredMaintenanceWindow: tue:17:00-tue:19:00
      ServerlessV2ScalingConfiguration: !If
        - IsServerlessV2
        - MinCapacity: 0
          MaxCapacity: 10
        - !Ref AWS::NoValue
      SnapshotIdentifier: !If
        - RestoreFromSnapshot
        - !Ref pRdsSnapshotRestore
        - !Ref AWS::NoValue
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value: !Sub
            - ${pProductName}-db-${ResourceName}
            - ResourceName: !If
                - IsDev
                - !Ref pCleanBranch
                - !Ref pEnvironment
      VpcSecurityGroupIds:
        - !Ref DbSecurityGrp

  RdsPrimary:
    Type: AWS::RDS::DBInstance
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F80
            reason: Deletion protection is enabled on the DB cluster level
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !If
        - IsProvisioned
        - !Ref pInstanceClass
        - db.serverless
      DBInstanceIdentifier: !Sub ${pDbInstanceName}-primary
      DBParameterGroupName: !If
        - IsMysql
        - !Ref MysqlDbInstanceParamGrp
        - !Ref PostgresDbInstanceParamGrp
      DBSubnetGroupName: !Ref DbSubnetGrp
      Engine: !Ref pDbEngine
      DBClusterIdentifier: !Ref DbCluster
      PubliclyAccessible: false
      PromotionTier: 1
      EnablePerformanceInsights: !Ref pPerformanceInsights
      Tags:
        - Key: Name
          Value: !Sub
            - ${pProductName}-primary-${ResourceName}
            - ResourceName: !If
                - IsDev
                - !Ref pCleanBranch
                - !Ref pEnvironment

  RdsReplica:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - RdsPrimary
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F80
            reason: Deletion  protection is enabled on the DB cluster level
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !If
        - IsProvisioned
        - !Ref pInstanceClass
        - db.serverless
      DBInstanceIdentifier: !Sub ${pDbInstanceName}-replica
      DBClusterIdentifier: !Ref DbCluster
      DBParameterGroupName: !If
        - IsMysql
        - !Ref MysqlDbInstanceParamGrp
        - !Ref PostgresDbInstanceParamGrp
      DBSubnetGroupName: !Ref DbSubnetGrp
      PubliclyAccessible: false
      Engine: !Ref pDbEngine
      PromotionTier: 2
      EnablePerformanceInsights: !Ref pPerformanceInsights
      Tags:
        - Key: Name
          Value: !Sub
            - ${pProductName}-replica-${ResourceName}
            - ResourceName: !If
                - IsDev
                - !Ref pCleanBranch
                - !Ref pEnvironment
    Condition: CreateReplica

  RdsScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - DbCluster
    Properties:
      MaxCapacity: 15
      MinCapacity: 1
      ResourceId: !Sub cluster:${pDbInstanceName}-cluster
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/rds.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_RDSCluster
      ScalableDimension: rds:cluster:ReadReplicaCount
      ServiceNamespace: rds
    Condition: HorizontalScaling

  AuroraScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${pProductName} Aurora scaling policy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref RdsScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: RDSReaderAverageCPUUtilization
        ScaleInCooldown: 600
        ScaleOutCooldown: 300
        TargetValue: 60.0
    Condition: HorizontalScaling

  ErrorLogGroup:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/rds/cluster/${pDbInstanceName}-cluster/error
      RetentionInDays: 30

  SlowQueryLogGroup:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/rds/cluster/${pDbInstanceName}-cluster/slowquery
      RetentionInDays: 30

Outputs:
  ClusterIdentifier:
    Description: The Aurora DB cluster identifier
    Value: !Ref DbCluster
    Export:
      Name: !Sub ${AWS::StackName}-ClusterIdentifier

  WriteEndpoint:
    Description: The write endpoint of the database
    Value: !GetAtt DbCluster.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-WriteEndpoint

  ReadEndpoint:
    Description: The read endpoint of the database
    Value: !GetAtt DbCluster.ReadEndpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-ReadEndpoint
