apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ala-alerts.labels" . | nindent 4 }}
  name: mysql-rds
spec:
  type: ExternalName
  externalName: {{ .Values.rds.externalName }}
  ports:
    - port: 3306
      targetPort: 3306