apiVersion: v1
kind: Service
metadata:
  name: {{ include "ala-alerts.fullname" . }}-service
  labels:
    {{- include "ala-alerts.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "ala-alerts.selectorLabels" . | nindent 4 }}