apiVersion: v1
kind: Service
metadata:
  name: service-{{ include "ala-alerts.fullname" . }}
  labels:
    {{- include "ala-alerts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "ala-alerts.selectorLabels" . | nindent 4 }}