AWSTemplateFormatVersion: "2010-09-09"
Description: Code pipeline for the alerts repo

Parameters:
  pAlertsStackName:
    Type: String
    Description: The name of the alerts stack
  pAutoDeploy:
    Type: String
    Description: Sets the pipeline to auto deploy on repo changes
  pBootstrapStackName:
    Type: String
    Description: the name of the bootstrap stack
  pBucketsStackName:
    Type: String
    Description: the name of the bucket stack
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pEksClusterName:
    Type: String
    Description: The name of the EKS cluster
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pGitHubBranch:
    Type: String
    Description: GitHub branch we're deploying from
  pGitHubOwner:
    Type: String
    Description: GitHub owner
  pGitHubRepositoryName:
    Type: String
    Description: GitHub repository name.
  pPipelineFingerprint:
    Type: String
    Description: The fingerprint of the pipeline, used to determine if it's been modified
  pProductComponent:
    Type: String
    Description: The name of the product component
  pProductName:
    Type: String
    Description: The name of the product
  pRestartExecutionOnUpdate:
    Type: String
    Description: Restart that pipeline if it's been updated
    AllowedValues:
         - true 
         - false

Conditions:

  IsDev: !Equals
    - !Ref pEnvironment
    - development
  AutoDeploy: !Equals
    - !Ref pAutoDeploy
    - true

Resources:
 
  ExportConfig:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub
              - ${pProductName}-${pProductComponent}-export-config-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: Load the environment and build the CloudFormation template config file
      ServiceRole:
               Fn::ImportValue:
                 Fn::Sub: ${pBootstrapStackName}-CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: ARTIFACTS_BUCKET
            Value:
              Fn::ImportValue:
                Fn::Sub: ${pBucketsStackName}-${AWS::Region}-CodePipelineArtifactBucketName
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub cicd/${pProductComponent}/pipeline/export_config_buildspec.yaml
      TimeoutInMinutes: 5

  BuildAlerts:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub
        - ${pProductName}-${pProductComponent}-build-alerts-${ResourceName}
        - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: Build the alerts project
      ServiceRole:
               Fn::ImportValue:
                 Fn::Sub: ${pBootstrapStackName}-CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub cicd/${pProductComponent}/pipeline/build_alerts_buildspec.yaml
      TimeoutInMinutes: 30

  DeployAlerts:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub
              - ${pProductName}-${pProductComponent}-deploy-alerts-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: Deploy alerts
      ServiceRole:
               Fn::ImportValue:
                 Fn::Sub: ${pBootstrapStackName}-CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub cicd/${pProductComponent}/pipeline/deploy_alerts_buildspec.yaml
      TimeoutInMinutes: 20

  DeployNotification:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub 
              - ${pProductName}-${pProductComponent}-deploy-notification-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: Send out the deploy notifications
      ServiceRole:
               Fn::ImportValue:
                 Fn::Sub: ${pBootstrapStackName}-CodeBuildServiceRoleArn
      Artifacts:                           
        Type: CODEPIPELINE                 
      Environment:                         
        Type: LINUX_CONTAINER              
        ComputeType: BUILD_GENERAL1_SMALL  
        Image: aws/codebuild/standard:5.0  
      Source:                             
        Type: CODEPIPELINE
        BuildSpec: !Sub cicd/${pProductComponent}/pipeline/deploy_notification_buildspec.yaml
      TimeoutInMinutes: 5

  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub
              - ${pProductName}-${pProductComponent}-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      PipelineType: V2
      RoleArn:
            Fn::ImportValue:
              Fn::Sub: ${pBootstrapStackName}-CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location:
              Fn::ImportValue:
                Fn::Sub: ${pBucketsStackName}-${AWS::Region}-CodePipelineArtifactBucketName
      DisableInboundStageTransitions:
        - Reason: To prevent accidental teardown
          StageName: Teardown
      RestartExecutionOnUpdate: !Ref pRestartExecutionOnUpdate
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            Push:
              - Branches:
                  Includes:
                    - !If [ AutoDeploy, !Ref pGitHubBranch, bogo-branch ]
                FilePaths:
                  Includes:
                    - !Sub cicd/${pProductComponent}/**
            SourceActionName: CheckoutSrc
      Variables:
        - Name: SRC_BRANCH
          DefaultValue: !Ref pGitHubBranch
          Description: The branch this pipeline is deploying from
        - Name: PIPELINE_FINGERPRINT
          DefaultValue: !Ref pPipelineFingerprint
          Description: The fingerprint of the pipeline, used to determine if it's been modified
      Stages:
      - Name: Checkout_Source
        Actions:
          - Name: CheckoutSrc
            ActionTypeId:
              Category: Source
              Owner: AWS
              Provider: CodeStarSourceConnection
              Version: 1
            Configuration:
              ConnectionArn:
                         Fn::ImportValue:
                           Fn::Sub: ${pBootstrapStackName}-CodestarConnectionArn
              FullRepositoryId: !Sub ${pGitHubOwner}/${pGitHubRepositoryName}
              BranchName: !Ref pGitHubBranch
              OutputArtifactFormat: CODEBUILD_CLONE_REF
              DetectChanges: !Ref pAutoDeploy
            Namespace: CheckoutSrcNS
            OutputArtifacts:
              - Name: 'SourceArtifact'
      - Name: Deploy_Infrastructure_Build
        Actions:
          - Name: ExportConfig
            ActionTypeId:
              Owner: AWS
              Category: Build
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref ExportConfig
              EnvironmentVariables: !Sub |
                 [
                   { "name":"CLEAN_BRANCH", "value":"${pCleanBranch}" },
                   { "name":"COMMIT_ID", "value":"#{CheckoutSrcNS.CommitId}" },
                   { "name":"ENVIRONMENT", "value":"${pEnvironment}" },
                   { "name":"PIPELINE_FINGERPRINT", "value":"#{variables.PIPELINE_FINGERPRINT}" },
                   { "name":"PRODUCT_COMPONENT", "value":"${pProductComponent}" },
                   { "name":"SRC_BRANCH", "value":"${pGitHubBranch}" }
                 ]
            Namespace: ExportConfigNS
            InputArtifacts:
              - Name: 'SourceArtifact'
            OutputArtifacts:
              - Name: ExportConfigArtifact
            RunOrder: 1

          - Name: DeployAlertsCFStack
            ActionTypeId:
              Owner: AWS
              Category: Deploy
              Version: 1
              Provider: CloudFormation
            Configuration:
              TemplatePath: !Sub 'ExportConfigArtifact::cicd/${pProductComponent}/app/#{ExportConfigNS.ALERTS_STACK_FILE_PFIX}.yaml'
              ActionMode: !If [ IsDev, REPLACE_ON_FAILURE, CREATE_UPDATE ]
              TemplateConfiguration: !Sub 'ExportConfigArtifact::cicd/${pProductComponent}/app/#{ExportConfigNS.ALERTS_STACK_FILE_PFIX}_template_config.json'
              Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
              RoleArn:
                   Fn::ImportValue:
                     Fn::Sub: '${pBootstrapStackName}-CloudFormationServiceRoleArn'
              StackName: !Ref pAlertsStackName
            InputArtifacts:
              - Name: 'ExportConfigArtifact'
            Namespace: AlertsCloudFormationOutNS
            OutputArtifacts: [ ]
            RunOrder: 2

          - Name: BuildAlerts
            ActionTypeId:
              Owner: AWS
              Category: Build
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref BuildAlerts
              EnvironmentVariables: !Sub |
                [
                  { "name":"ALERTS_ECR_REPOSITORY", "value":"#{AlertsCloudFormationOutNS.AlertsRepositoryArn}" },
                  { "name":"CLEAN_BRANCH", "value":"${pCleanBranch}" },
                  { "name":"COMMIT_ID", "value":"#{CheckoutSrcNS.CommitId}" },
                  { "name":"ENVIRONMENT", "value":"${pEnvironment}" },
                  { "name":"PIPELINE_FINGERPRINT", "value":"#{variables.PIPELINE_FINGERPRINT}" },
                  { "name":"SRC_BRANCH", "value":"${pGitHubBranch}" }
                ]
            InputArtifacts:
              - Name: 'SourceArtifact'
            RunOrder: 3

          - Name: Approval
            ActionTypeId:
              Owner: AWS
              Category: Approval
              Version: 1
              Provider: Manual
            Configuration:
              CustomData: Approval required to deploy build to eks
            RunOrder: 4

          - Name: DeployAlerts
            ActionTypeId:
              Owner: AWS
              Category: Build
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref DeployAlerts
              EnvironmentVariables: !Sub |
                [
                  { "name":"ALERTS_ECR_REPOSITORY", "value":"#{AlertsCloudFormationOutNS.AlertsRepositoryArn}" },
                  { "name":"CLEAN_BRANCH", "value":"${pCleanBranch}" },
                  { "name":"COMMIT_ID", "value":"#{CheckoutSrcNS.CommitId}" },
                  { "name":"EKS_CLUSTER_NAME", "value":"${pEksClusterName}" },
                  { "name":"ENVIRONMENT", "value":"${pEnvironment}" },
                  { "name":"PIPELINE_FINGERPRINT", "value":"#{variables.PIPELINE_FINGERPRINT}" },
                  { "name":"SRC_BRANCH", "value":"${pGitHubBranch}" }
                ]
            InputArtifacts:
              - Name: 'SourceArtifact'
            RunOrder: 5

          - Name: DeployNotification
            ActionTypeId:
              Owner: AWS
              Category: Build
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref DeployNotification
              EnvironmentVariables: !Sub |
                [
                  { "name":"AUTHOR", "value":"#{CheckoutSrcNS.AuthorDisplayName}" },
                  { "name":"CLEAN_BRANCH", "value":"${pCleanBranch}" },
                  { "name":"COMMIT_ID", "value":"#{CheckoutSrcNS.CommitId}" },
                  { "name":"ENVIRONMENT", "value":"${pEnvironment}" },
                  { "name":"PRODUCT_COMPONENT", "value":"#{ExportConfigNS.PRODUCT_COMPONENT}" },
                  { "name":"PRODUCT_NAME", "value":"#{ExportConfigNS.PRODUCT_NAME}" },
                  { "name":"REPO", "value":"#{CheckoutSrcNS.FullRepositoryName}" },
                  { "name":"SLACK_ALERT_CHANNEL", "value":"#{ExportConfigNS.SLACK_ALERT_CHANNEL}" },
                  { "name":"SLACK_DEPLOY_NOTIFICATION", "value":"#{ExportConfigNS.SLACK_DEPLOY_NOTIFICATION}" },
                  { "name":"SRC_BRANCH", "value":"${pGitHubBranch}" }
                ]
            Namespace: DeployNotificationNS
            InputArtifacts:
              - Name: 'SourceArtifact'
            RunOrder: 6

      - Name: Teardown
        Actions:
          - Name: Approval
            ActionTypeId:
              Owner: AWS
              Category: Approval
              Version: 1
              Provider: Manual
            Configuration:
              CustomData: Approval required to tear down this stack
            RunOrder: 1
          - Name: TeardownAlertsStack
            ActionTypeId:
              Owner: AWS
              Category: Deploy
              Version: 1
              Provider: CloudFormation
            Configuration:
              ActionMode: DELETE_ONLY
              StackName: !Ref pAlertsStackName
              RoleArn:
                Fn::ImportValue:
                  Fn::Sub: '${pBootstrapStackName}-CloudFormationServiceRoleArn'
            RunOrder: 2
          - Name: ApprovalForPipelineTeardown
            ActionTypeId:
              Owner: AWS
              Category: Approval
              Version: 1
              Provider: Manual
            Configuration:
              CustomData: Approval required to tear down this stack
            RunOrder: 3
          - Name: TeardownCodePipeline
            ActionTypeId:
              Owner: AWS
              Category: Deploy
              Version: 1
              Provider: CloudFormation
            Configuration:
              ActionMode: DELETE_ONLY
              StackName: !Ref AWS::StackName
              RoleArn:
                   Fn::ImportValue:
                     Fn::Sub: '${pBootstrapStackName}-CloudFormationServiceRoleArn'
            RunOrder: 4

  BuildAlertsCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/codebuild/${BuildAlerts}
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  DeployAlertsCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/codebuild/${DeployAlerts}
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  ExportConfigCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/codebuild/${ExportConfig}
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  NotificationCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/codebuild/${DeployNotification}
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName


Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
