version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
  secrets-manager:
    DOCKER_USERNAME: ala-secrets-production:dockerhub-username
    DOCKER_PASSWORD: ala-secrets-production:dockerhub-password
  exported-variables:
    - BUILD_TAG

phases:
  install:
    commands:
      - echo Installing dependencies...
      - java -version
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the project...
      - ./gradlew clean
      - ./gradlew build --stacktrace
      - ./gradlew bootWar

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
      - rm -rf build/libs/*-plain.war
      - echo Building the Docker image...
      - docker build -t ala-alerts .
      - echo Tagging the Docker image...
      - BUILD_TAG=$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER
      - echo build tag is $BUILD_TAG
      - echo "$BUILD_TAG" > /tmp/build_tag.txt
      - echo tagging
      - docker tag ala-alerts:latest $ECR_REPO:$BUILD_TAG
      - docker tag ala-alerts:latest $ECR_REPO:latest
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REPO:$BUILD_TAG
      - docker push $ECR_REPO:latest

cache:
  paths:
    - '/root/.cache/docker/**/*'
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '/root/.m2/repository/**/*'

artifacts:
  files:
    - /tmp/build_tag.txt
  discard-paths: yes