version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cat /etc/lsb-release
      - apt update -y
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  build:
    commands:
      - echo Build started on $(date)
      - aws eks --region ap-southeast-2 update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl config set-context --current --namespace=alerts
      - kubectl delete secret alerts-config-secret-$CLEAN_BRANCH || true
      - eksctl delete iamserviceaccount --name=alerts-service-account-$CLEAN_BRANCH --namespace=alerts --cluster=$EKS_CLUSTER_NAME
      - helm uninstall $HELM_RELEASE_NAME -n alerts
  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)

artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - '**/*'