# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

secret:
  name: "alerts-config-secret"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "alb"
  certificateArn: ""
  hostname: ""
  tls: []

resources:
  limits:
    memory: 4096Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

rds:
  name: "mysql-rds"
  externalName: "mysql-rds"

# Config file properties
config:
  base:
    alerts_base_url: "https://www-test.ala.org.au"
    alerts_context_path: ""
  cas:
    auth_base_url: "https://auth-test.ala.org.au"
    alerts_apikey_whitelist: ""
  db:
    driver_class_name: "com.mysql.jdbc.Driver"
    alerts_db_hostname: "mysql-rds"
    database_name: ""
    alerts_db_username: "admin"
    alerts_db_password: ""
    mysql_connection_ssl: "False"
    dataSource_dbCreate: "update"
  enable_myannotation: "true"
  enable_specieslists_alerts: "true"
  enable_spatial_alerts: "true"
  enable_blogs_alerts: "true"
  enable_citizen_science_alerts: "true"
  external:
    biocache_url: "https://biocache-test.ala.org.au"
    biocache_service_url: "https://biocache-ws-test.ala.org.au"
    spatial_url: "https://spatial.ala.org.au"
    collectory_url: "https://collections-test.ala.org.au"
    alerts_collectory_service_url: "https://api.test.ala.org.au/metadata"
    alerts_userdetails_url: "https://api.test.ala.org.au/userdetails/cognito//userDetails/getUserListFull"
    lists_url: "https://lists-test.ala.org.au"
  mail:
    enable_email: "true"
    mail_ses_enabled: "true"
  header_and_footer_baseurl: "https://www-test-2023.ala.org.au/commonui-bs3-2019"
  header_and_footer_version: "2"
  ala_base_url: "https://www.ala.org.au"
  bie_base_url: "https://bie-test.ala.org.au"
  bie_search_path: "/search"
  alerts_skin_layout: "ala-main"
  skin_home_url: "http://www.ala.org.au"
  skin_orgNameLong: "Atlas of Living Australia (TEST)"
  orgNameShort: "ALA"
  orgSupportEmail: "support@ala.org.au"
  alerts_site_default_language: "en"
  skin_favicon: "https://www.ala.org.au/app/uploads/2019/01/cropped-favicon-32x32.png"
  privacy_policy_url: "https://www.ala.org.au/about/terms-of-use/privacy-policy/"
  occurrence_searchTitle: "occurrence search"
  occurrence_searchUrl: "https://biocache-test.ala.org.au/occurrences/search?q=passer"
  regions_searchTitle: "ACT"
  regions_searchUrl: "http://regions-test.ala.org.au/states/Australian+Capital+Territory"
  speciesPages_searchTitle: "Shingle-back"
  speciesPages_searchUrl: "https://bie.ala.org.au/species/Tiliqua+rugosa"
  collection_searchTitle: "ANIC"
  collection_searchUrl: "https://collections.ala.org.au/public/show/co13"
  google_apikey: ""
  biosecurity:
    biosecurity_more_info: ""
    biosecurity_query_url: "/occurrences/search?q=species_list_uid:___LISTIDPARAM___&fq=decade:2020&fq=country:Australia&fq=first_loaded_date:[___DATEPARAM___%20TO%20*]&fq=occurrence_date:[___LASTYEARPARAM___%20TO%20*]&sort=first_loaded_date&dir=desc&disableAllQualityFilters=true"
  species_list_server: "https://lists-test.ala.org.aut"
  csv:
    biosecurity_csv_local_enabled: "false"
    biosecurity_csv_s3_enabled: "true"
  s3:
    grails_plugin_awssdk_region: "ap-southeast-2"
    grails_plugin_awssdk_s3_bucket: "ala-alerts"
    grails_plugin_awssdk_s3_profile: ""
  cognito:
    oidc:
      alerts_client_id: ""
      alerts_client_secret: ""
      discoveryUri: "https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39/.well-known/openid-configuration"
      logoutUrl: "https://auth-secure.auth.ap-southeast-2.amazoncognito.com/logout"
      alaUseridClaim: "username"
      logoutAction: "cognito"
      scope: "openid profile email ala/attrs ala/roles"
    core:
      roleAttribute: "ala:role"
      affiliation_survey_enabled: "true"
      auth_cookie_name: "ALA-Auth-Test"
    cookie:
      auth_cookie_enabled: "true"
      auth_cookie_domain: ".ala.org.au"
    jwt:
      rolesFromAccessToken: "true"
      userIdClaim: "username"
      roleClaims: "cognito:groups"
      discoveryUri: "https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39/.well-known/openid-configuration"

  apikey:
    apikey_check_enabled: "true"
    apikey_auth_url: "https://auth-test.ala.org.au/apikey/"
    apikey_check_url: "https://auth-test.ala.org.au/apikey/ws/check?apikey="
    apikey_userdetails_url: "https://auth-test.ala.org.au/userdetails/"
  webservice:
    webservice_jwt: "true"
    alerts_webservice_jwt_scopes: "ala/internal users/read ala/attrs"
    alerts_client_id: ""
    alerts_client_secret: ""
  usersync_batchsize: "1000"
  userdetails:
    userdetails_url: "https://api.test.ala.org.au/userdetails/cognito/"
    userdetails_web_url: "https://aws-auth-test-2023.test.ala.org.au/userdetails/"
    userdetails_api_url: "https://api.test.ala.org.au/userdetails/cognito/"
  openapi:
    openapi_oauth_url: "https://auth-secure.auth.ap-southeast-2.amazoncognito.com/oauth2"
    terms_url: "https://www.ala.org.au/terms-of-use/"
    support_email: "support@ala.org.au"