version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt update -y
        && cat /etc/lsb-release
        && apt-get -q -y install openjdk-11-jdk
        && apt-get -q -y install unzip
        && apt-get -q -y install zip
        && apt-get -q -y install curl
        && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        && apt-get update
        && apt-get install -y docker-ce
        && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        && chmod 700 get_helm.sh
        && ./get_helm.sh
        && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        && chmod +x kubectl
        && mv kubectl /usr/local/bin/

  build:
    commands:
      - echo Build started on $(date)
      - aws eks --region ap-southeast-2 update-kubeconfig --name $EKS_CLUSTER_NAME
      - printf "$(kubectl config current-context)\n"
      - cd helm
      - helm upgrade --install ala-alerts . --set image.tag=$CLEAN_BRANCH

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
